/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface AuthenticationExtensionsPrfInputs {
  
}
export interface PublicKeyCredentialDescriptor {
  id: Buffer
  transports?: Array<string> | undefined
  type: string
}
export interface AuthenticationExtensionsClientInputs {
  appid?: string | undefined
  credProps?: boolean | undefined
  hmacCreateSecret?: boolean | undefined
  minPinLength?: boolean | undefined
  prf?: AuthenticationExtensionsPRFInputs | undefined
}
export interface PublicKeyCredentialParameters {
  alg: number
  type: string
}
export interface PublicKeyCredentialEntity {
  name: string
}
export interface PublicKeyCredentialRpEntity {
  id?: string | undefined
  name: string
}
export interface PublicKeyCredentialUserEntity {
  displayName: string
  id: Buffer
  name: string
}
export interface AuthenticatorSelectionCriteria {
  authenticatorAttachment?: string | undefined
  requireResidentKey?: boolean | undefined
  residentKey?: string | undefined
  userVerification?: "discouraged" | "preferred" | "required" | undefined
}
export interface PublicKeyCredentialCreationOptions {
  attestation?: "direct" | "enterprise" | "indirect" | "none" | undefined
  authenticatorSelection?: AuthenticatorSelectionCriteria | undefined
  challenge: Buffer
  excludeCredentials?: Array<PublicKeyCredentialDescriptor> | undefined
  extensions?: AuthenticationExtensionsClientInputs | undefined
  pubKeyCredParams: Array<PublicKeyCredentialParameters>
  rp: PublicKeyCredentialRpEntity
  timeout?: number | undefined
  user: PublicKeyCredentialUserEntity
}
export interface PublicKeyCredentialRequestOptions {
  allowCredentials?: Array<PublicKeyCredentialDescriptor> | undefined
  challenge: Buffer
  extensions?: AuthenticationExtensionsClientInputs | undefined
  rpId?: string | undefined
  timeout?: number | undefined
  userVerification?: "discouraged" | "preferred" | "required" | undefined
}
export interface PublicKeyCredential {
  id: string
  rawId: Buffer
  response: Buffer
  authenticatorAttachment?: string | undefined
  type: string
}
/** Create a new WebAuthn credential */
export declare function create(options: PublicKeyCredentialCreationOptions): Promise<PublicKeyCredential>
/** Get/authenticate with an existing WebAuthn credential */
export declare function get(options: PublicKeyCredentialRequestOptions): Promise<PublicKeyCredential>
export declare function isSupported(): Promise<boolean>
