/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface PublicKeyCredentialRpEntity {
  id?: string | undefined
  name: string
}
export interface PublicKeyCredentialUserEntity {
  id: Buffer
  name: string
  displayName: string
}
export interface PublicKeyCredentialParameters {
  type: string
  alg: number
}
export interface AuthenticatorSelectionCriteria {
  authenticatorAttachment?: string | undefined
  requireResidentKey?: boolean | undefined
  residentKey?: string | undefined
  userVerification?: string | undefined
}
export interface PublicKeyCredentialDescriptor {
  type: string
  id: Buffer
  transports?: Array<string> | undefined
}
export interface PublicKeyCredentialCreationOptions {
  rp: PublicKeyCredentialRpEntity
  user: PublicKeyCredentialUserEntity
  challenge: Buffer
  pubKeyCredParams: Array<PublicKeyCredentialParameters>
  timeout?: number | undefined
  excludeCredentials?: Array<PublicKeyCredentialDescriptor> | undefined
  authenticatorSelection?: AuthenticatorSelectionCriteria | undefined
  attestation?: string | undefined
}
export interface PublicKeyCredentialRequestOptions {
  challenge: Buffer
  timeout?: number | undefined
  rpId?: string | undefined
  allowCredentials?: Array<PublicKeyCredentialDescriptor> | undefined
  userVerification?: string | undefined
}
export interface AuthenticatorAttestationResponse {
  clientDataJson: Buffer
  attestationObject: Buffer
  transports: Array<string>
}
export interface AuthenticatorAssertionResponse {
  clientDataJson: Buffer
  authenticatorData: Buffer
  signature: Buffer
  userHandle?: Buffer | undefined
}
export interface PublicKeyCredential {
  id: string
  rawId: Buffer
  response: AuthenticatorAttestationResponse | AuthenticatorAssertionResponse
  authenticatorAttachment?: string | undefined
  type: string
}
/** Create a new WebAuthn credential */
export declare function create(options: PublicKeyCredentialCreationOptions): PublicKeyCredential
/** Get/authenticate with an existing WebAuthn credential */
export declare function get(options: PublicKeyCredentialRequestOptions): PublicKeyCredential
